apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name:  {{ include "argo-nginx.fullname" . }}
  labels:
    {{- include "argo-nginx.labels" . | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  host: argo-nginx-{{ .Release.Namespace }}.{{ .Values.global.domain }}
  port:
    targetPort: {{ .Values.service.port }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: http
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
      - lastTransitionTime: null
        status: 'True'
        type: Admitted
    routerName: router
    wildcardPolicy: None